/* Automatically generated by cbindgen. Do not edit manually please. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define EthernetType_IPV4_HEX 2048

/**
 * Fixed header size: 6 (dest MAC) + 6 (src MAC) + 2 (EtherType).
 */
#define EthernetHeader_SIZE 14

/**
 * Result of classifying one packet. Returned by value — no heap
 * allocation, so it's cheap to return per-packet on VPP's hot path.
 */
typedef struct ClassifyResult {
  bool is_valid;
  uint8_t protocol;
  uint16_t dest_port;
  uint32_t error_code;
} ClassifyResult;

/**
 * Classifies a raw Ethernet/IPv4/UDP packet: valid UDP, or rejected with
 * a reason.
 *
 * Does no allocation and does not take ownership of `data`; it only reads
 * through the pointer for the duration of the call.
 *
 * # Safety
 * Caller (the VPP dispatch function) must ensure:
 * - `data` is either null, or points to at least `len` initialized,
 *   readable bytes for the duration of this call (e.g. `vlib_buffer_t`'s
 *   current data region — VPP guarantees that region is contiguous and
 *   valid for `current_length` bytes).
 * - The memory `data` points to is not mutated concurrently from another
 *   thread while this call runs.
 *
 * Validated here: `data.is_null()` is checked before any dereference: a
 * null pointer returns `CParseError::NullPointer` instead of touching
 * memory. Everything past that point goes through `parse_packet`, which
 * itself bounds-checks `len` against every header/field it reads (see
 * `ethernet::parse_ethernet_header`, `ipv4::parse_ipv4_header`,
 * `udp::parse_udp_packet`) — so a short or truncated buffer is rejected
 * with a `ParseError`, never read past its end.
 */
struct ClassifyResult packet_classify(const uint8_t *data, uintptr_t len);
